language: python

dist: xenial

env:
  global:
    - TEST_DIR=/tmp/pastis # folder where the tests are run from
    - CACHED_BUILD_DIR="cached"

matrix:
  include:
    # Ubuntu 14.04 versions
    - name: "Python 2.7"
      python: 2.7
      env: TEST=TRUE NUMPY_VERSION=1.16 SCIPY_VERSION=1.2  PANDAS_VERSION=* SKLEARN_VERSION=0.20 AUTOGRAD_VERSION=* COOLER_VERSION=*
    - name: "Python 3.6"
      python: 3.6
      env: TEST=TRUE NUMPY_VERSION=1.16 SCIPY_VERSION=0.19  PANDAS_VERSION=0.25 SKLEARN_VERSION=0.18 AUTOGRAD_VERSION=1.2 COOLER_VERSION=0.8.10 COVERAGE=true
    - name: "Python 3.6 + recent sklearn"
      python: 3.6
      env: TEST=TRUE NUMPY_VERSION=1.17 SCIPY_VERSION=1.3.1 PANDAS_VERSION=0.25  SKLEARN_VERSION=0.21 AUTOGRAD_VERSION=1.2 COOLER_VERSION=0.8.10 COVERAGE=true BUILD_DOC=true
    #Â - name: "Python 3.7"
    #   python: 3.7
    #  env: TEST=TRUE COVERAGE=TRUE NUMPY_VERSION=1.17 SCIPY_VERSION=1.3 PANDAS_VERSION="*"  SKLEARN_VERSION="*"

install: 
    - source build_tools/travis/install.sh

before_script:
    - make clean

script:
    - bash build_tools/travis/test_script.sh

after_success:
    # Ignore coveralls failures as the coveralls server is not very reliable
    # but we don't want travis to report a failure in the github UI just
    # because the coverage report failed to be published.
    # coveralls need to be run from the git checkout
    # so we need to copy the coverage results from TEST_RUN_FOLDER
    - bash build_tools/travis/after_success.sh
