language: python

dist: xenial

notifications:
  email: false

env:
  global:
    - TEST_DIR="/tmp/pastis" # folder where the tests are run from

  matrix:
    # Ubuntu 14.04 versions
    - DISTRIB="conda" PYTHON_VERSION="2.7"
      NUMPY_VERSION="1.8.2" SCIPY_VERSION="0.14.0"
      SKLEARN_VERSION="0.14" PANDAS_VERSION="0.14.0"
    - DISTRIB="conda" PYTHON_VERSION="3.6"
      NUMPY_VERSION="1.11.2" SCIPY_VERSION="0.18.1"
      SKLEARN_VERSION="0.18" PANDAS_VERSION="0.19.1" 
    - DISTRIB="conda" PYTHON_VERSION="3.7"
      NUMPY_VERSION="1.17" SCIPY_VERSION="*"
      SKLEARN_VERSION="*"  PANDAS_VERSION="*"

install: 
    - source continuous_integration/install.sh

before_script:
    - make clean

script:
    - python continuous_integration/show-python-packages-versions.py
    # We want to back out of the current working directory to make
    # sure we are using pastis installed in site-packages rather
    # than the one from the current working directory
    # Parentheses (run in a subshell) are used to leave
    # the current directory unchanged
    - bash continuous_integration/test_script.sh

after_success:
    # Ignore coveralls failures as the coveralls server is not very reliable
    # but we don't want travis to report a failure in the github UI just
    # because the coverage report failed to be published.
    # coveralls need to be run from the git checkout
    # so we need to copy the coverage results from TEST_RUN_FOLDER
    - if [[ "$COVERAGE" == "true" ]]; then cp "$TEST_RUN_FOLDER/.coverage" .; coveralls || echo "failed"; fi
