language: python

dist: xenial

env:
  global:
    - TEST_RUN_FOLDER="/tmp" # folder where the tests are run from
    - CACHED_BUILD_DIR="cached"

matrix:
  include:
    # Ubuntu 14.04 versions
    - name: "Python 2.7"
      python: 2.7
      env: TEST=TRUE NUMPY_VERSION=1.13 SCIPY_VERSION=0.12  PANDAS_VERSION=* SKLEARN_VERSION=0.15
    - name: "Python 3.6"
      python: 3.6
      env: TEST=TRUE NUMPY_VERSION=1.14 SCIPY_VERSION=0.19  PANDAS_VERSION=0.25 SKLEARN_VERSION=0.18 COVERAGE=TRUE
    - name: "Python 3.6 + recent sklearn"
      python: 3.6
      env: TEST=TRUE NUMPY_VERSION=1.17 SCIPY_VERSION=1.3.1 PANDAS_VERSION=0.25  SKLEARN_VERSION=0.21 COVERAGE=TRUE
    #Â - name: "Python 3.7"
    #   python: 3.7
    #  env: TEST=TRUE COVERAGE=TRUE NUMPY_VERSION=1.17 SCIPY_VERSION=1.3 PANDAS_VERSION="*"  SKLEARN_VERSION="*"

install: 
    - source continuous_integration/install.sh

before_script:
    - make clean

script:
    - python continuous_integration/show-python-packages-versions.py
    # We want to back out of the current working directory to make
    # sure we are using pastis installed in site-packages rather
    # than the one from the current working directory
    # Parentheses (run in a subshell) are used to leave
    # the current directory unchanged
    - bash continuous_integration/test_script.sh

after_success:
    # Ignore coveralls failures as the coveralls server is not very reliable
    # but we don't want travis to report a failure in the github UI just
    # because the coverage report failed to be published.
    # coveralls need to be run from the git checkout
    # so we need to copy the coverage results from TEST_RUN_FOLDER
    - bash build_tools/travis/after_success.sh
